name: SonarQube Scan

on:
  push:
    branches:
      - main
  

jobs:
  sonarqube-scan:
    name: sonarqube-scan
    runs-on: self-hosted
    permissions: read-all
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: |
          sonar-scanner \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.token=${{ secrets.SONAR_TOKEN }}
